"""Pydantic models for AI Hospital Customer Care System."""
from .schemas import (
    PatientProfile,
    Complaint,
    MedicalHistory,
    ManagerDecision,
    SpecialistAssessment,
    ClinicalRecommendation,
    ReviewResult,
    AppointmentSlot,
    DoctorInfo,
    IntakeData,
    Department,
    Priority,
    Urgency,
    Verdict,
    Status,
)

__all__ = [
    "PatientProfile",
    "Complaint",
    "MedicalHistory",
    "ManagerDecision",
    "SpecialistAssessment",
    "ClinicalRecommendation",
    "ReviewResult",
    "AppointmentSlot",
    "DoctorInfo",
    "IntakeData",
    "Department",
    "Priority",
    "Urgency",
    "Verdict",
    "Status",
]
